---
- name: Install all applications given below list
  hosts: all
  become: 1
  vars:
    - apps: [vim,ping]

  tasks:
  - name: install application
    apt:
      name: "{{ item }}"
      state: present
    with_item: "{{ apps }}"

  - name:
      user: "{{ item }}"
      shell: /bin/bash
      comments: QA Team,Dev team
    loops:
      - basant
      - mohanty
      - kumar
