---
# tasks file for webserver
- name: install nginx
  apt:
    name: "{{ nginx_package_name }}"
    state: present
  become: true
- name: Pleace custom HTML file
  copy:
    src: index.html
    dest: /var/www/html/index.html
  become: true

- name:
  service:
    name: "{{ nginx_package_name }}"
    state: started
    enabled: yes
  become: true

